variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - cd backend/

stages:
  - build
  - test
  - deploy
  - generate-time-spend-report

generate-time-spend-report:
  stage: generate-time-spend-report
  image: python:3
  script:
    - cd ../.gitlab/time_track/
    - pip3 install -r requirements.txt
    - echo $CI_SERVER_URL
    - echo $CI_PROJECT_URL
    - echo $GITLAB_PERSONAL_ACCESS_TOKEN
    - python3 time_track.py $CI_SERVER_URL $GITLAB_PERSONAL_ACCESS_TOKEN $CI_PROJECT_URL
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule" && $CI_COMMIT_BRANCH == "dev"'
      when: always
    - when: never

build:
  stage: build
  script: gradle --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

check_code_style:
  stage: test
  script: gradle spotlessCheck
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

run-tests:
  stage: test
  script: gradle check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle

release:
  stage: deploy
  script: echo "No release stage is specified yet."
  only:
    - dev