version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - FRONTEND_URL=${FRONTEND_URL:-http://localhost:80}
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
    ports:
      - 8080:8080
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:80}
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
      - PREFILL_DATABASE=true
    depends_on:
      - db
    networks:
      - backend_network
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
    ports:
      - 80:80
    environment:
      - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=studiosus
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
    - backend_network
volumes:
  postgres_data:
networks:
  backend_network:
    driver: bridge