version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - FRONTEND_URL=${FRONTEND_URL:-http://localhost:80}
    ports:
      - 8080:8080
    environment:
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:80}
      - PREFILL_DATABASE=true
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-dev}
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - BACKEND_URL=${BACKEND_URL:-http://localhost:8080}
    ports:
      - 80:80
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=studiosus
    volumes:
      - postgres_data:/var/lib/postgresql/data/
volumes:
  postgres_data: